package com.alecs.onlinetheater.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@Entity
//@ApiModel(value = "Plan", description = "Plans are the options you can choose between in order " +
//        "to get access in the online theater")
public class Plan {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @ApiModelProperty(position = 0, notes = "The ID of the plan generated by database.")
    private Integer planId;
    @NotNull(message = "Plan name can not be null!")
    @NotEmpty(message = "Plan name can not be empty!")
    @Length(min=3, max = 15, message = "Plan name can have a length between 3 and 15 characters!")
//    @ApiModelProperty(position = 1, notes = "The name of the plan. Choose a suggestive one!")
    private String planName;
    @NotEmpty(message = "Plan description can not be empty!")
    @Length(min=3, max = 500, message = "Plan description can have a length between 3 and 500 characters!")
//    @ApiModelProperty(position = 2, notes = "Short description of the plan. You can add here the benefits of the plan.")
    private String planDescription;
    @Min(value = 1, message = "Price should be at least 1!")
//    @ApiModelProperty(position = 3, notes = "Price of the plan in RON")
    private Integer price;

    public Plan() {
    }

    public Plan(String planName, String planDescription, Integer price) {
        this.planName = planName;
        this.planDescription = planDescription;
        this.price = price;
    }

    public Plan(Integer planId, String planName, String planDescription, Integer price) {
        this.planId = planId;
        this.planName = planName;
        this.planDescription = planDescription;
        this.price = price;
    }

    public Integer getPlanId() {
        return planId;
    }

    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public String getPlanName() {
        return planName;
    }

    public void setPlanName(String planName) {
        this.planName = planName;
    }

    public String getPlanDescription() {
        return planDescription;
    }

    public void setPlanDescription(String planDescription) {
        this.planDescription = planDescription;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }
}
