package com.alecs.onlinetheater.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@ApiModel(value = "Subscription", description = "The subscription makes the connection between plans and spectators. " +
        "Every spectator have a subscription based on a plan in order to watch a play.")
public class Subscription {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(position = 0, notes = "The ID of the plan generated by database.")
    private Integer subscriptionId;
    @ApiModelProperty(position = 1, notes = "The moment in time when the spectator bought the subscription")
    private LocalDateTime subscriptionStartDate;
    @ApiModelProperty(position = 2, notes = "The moment in time when the subscription expire (30 days after the subscription was bought).")
    private LocalDateTime subscriptionEndDate;

    @OneToOne
    @JoinColumn(name="spectator_id")
    @JsonIgnore
    private Spectator spectator;

    @ManyToOne
    @JoinColumn(name = "plan_id")
    private Plan subscriptionPlan;

    public Subscription() {
    }

    public Subscription(LocalDateTime subscriptionStartDate, LocalDateTime subscriptionEndDate) {
        this.subscriptionStartDate = subscriptionStartDate;
        this.subscriptionEndDate = subscriptionEndDate;
    }

    public Integer getSubscriptionId() {
        return subscriptionId;
    }

    public void setSubscriptionId(Integer subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    public LocalDateTime getSubscriptionStartDate() {
        return subscriptionStartDate;
    }

    public void setSubscriptionStartDate(LocalDateTime subscriptionStartDate) {
        this.subscriptionStartDate = subscriptionStartDate;
    }

    public LocalDateTime getSubscriptionEndDate() {
        return subscriptionEndDate;
    }

    public void setSubscriptionEndDate(LocalDateTime subscriptionEndDate) {
        this.subscriptionEndDate = subscriptionEndDate;
    }

    public Plan getSubscriptionPlan() {
        return subscriptionPlan;
    }

    public void setSubscriptionPlan(Plan subscriptionPlan) {
        this.subscriptionPlan = subscriptionPlan;
    }

    public Spectator getSpectator() {
        return spectator;
    }

    public void setSpectator(Spectator spectator) {
        this.spectator = spectator;
    }
}
